/**
 * THE DEVIL'S EYE - Cinema Intelligence Sample Data
 * Authentic high-fidelity projects and cinema multimodal data.
 */

import { Project, VoiceActor } from '../types';

export const VOICE_ACTORS: VoiceActor[] = [
  {
    id: 'voice-titan',
    name: 'Ares (Cinematic Deep)',
    category: 'Cinematic Epic',
    gender: 'male',
    accent: 'US Cinematic Low Bass',
    previewAudio: '/audio/preview-ares.mp3',
    rating: 9.9,
  },
  {
    id: 'voice-valkyrie',
    name: 'Athena (Analytical Mind)',
    category: 'Documentary Historian',
    gender: 'female',
    accent: 'British Documentary',
    previewAudio: '/audio/preview-athena.mp3',
    rating: 9.8,
  },
  {
    id: 'voice-noir',
    name: 'Colt (Gritty Detective)',
    category: 'Noir Detective',
    gender: 'male',
    accent: 'US Hard-boiled Noir',
    previewAudio: '/audio/preview-colt.mp3',
    rating: 9.7,
  },
  {
    id: 'voice-hyper',
    name: 'Nova (Viral Pacing)',
    category: 'Hyper Hype',
    gender: 'female',
    accent: 'US Modern Creator',
    previewAudio: '/audio/preview-nova.mp3',
    rating: 9.6,
  },
  {
    id: 'voice-shadow',
    name: 'Cipher (Whisper Suspense)',
    category: 'Suspense Thriller',
    gender: 'synthetic',
    accent: 'Neutral Cybernetic',
    previewAudio: '/audio/preview-cipher.mp3',
    rating: 9.7,
  },
];

export const DEMO_PROJECTS: Project[] = [
  {
    id: 'proj-inception',
    title: 'Inception: The Architecture of the Mind',
    type: 'movie',
    director: 'Christopher Nolan',
    year: 2010,
    genre: ['Action', 'Sci-Fi', 'Psychological Thriller'],
    synopsis: 'A skilled thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    duration: '02:28:00',
    durationSec: 8880,
    resolution: '1080p (1920x1080)',
    fps: 24,
    posterUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=600&q=80',
    videoSourceUrl: 'Inception.mp4',
    status: 'ready',
    lastEdited: '10 mins ago',
    createdAt: '2026-09-08',
    analysis: {
      overallScore: 92,
      charactersCount: 12,
      keyEventsCount: 38,
      twistsCount: 7,
      suspensePointsCount: 14,
      emotionalMomentsCount: 9,
      narrationSyncScore: 96,
      sceneMatchingScore: 94,
      audioScore: 90,
      subtitlesScore: 97,
      pacingScore: 91,
      continuityScore: 89,
    },
    scenes: [
      {
        id: 'scene-042',
        sceneNumber: 42,
        timestampStart: '01:14:32',
        timestampEnd: '01:16:08',
        startSec: 4472,
        endSec: 4568,
        location: 'First Dream Level - Rainstorm City Van',
        timeOfDay: 'day',
        characters: ['Dom Cobb', 'Saito', 'Ariadne', 'Fischer'],
        keyEvent: 'The kick synchronization failure due to militarized subconscious defenses',
        twistScore: 88,
        suspenseScore: 95,
        emotionalScore: 82,
        confidence: 98,
        thumbnail: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=500&q=80',
        dialogueCount: 14,
        tags: ['Dream Layer 1', 'Van Chase', 'Subconscious Defenses', 'Time Dilation'],
      },
      {
        id: 'scene-043',
        sceneNumber: 43,
        timestampStart: '01:16:09',
        timestampEnd: '01:18:40',
        startSec: 4569,
        endSec: 4720,
        location: 'Second Dream Level - Hotel Corridor',
        timeOfDay: 'interior',
        characters: ['Arthur', 'Dom Cobb', 'Fischer'],
        keyEvent: 'Zero gravity hallway brawl as the van enters freefall',
        twistScore: 74,
        suspenseScore: 92,
        emotionalScore: 70,
        confidence: 94,
        thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=500&q=80',
        dialogueCount: 8,
        tags: ['Zero-G', 'Hotel Corridor', 'Rotating Gravity', 'Practical Stunts'],
      },
      {
        id: 'scene-044',
        sceneNumber: 44,
        timestampStart: '01:18:41',
        timestampEnd: '01:21:15',
        startSec: 4721,
        endSec: 4875,
        location: 'Third Dream Level - Snow Fortress',
        timeOfDay: 'day',
        characters: ['Eames', 'Saito', 'Fischer'],
        keyEvent: 'Saito succumbs to mortal wound, threatening descent into Limbo',
        twistScore: 84,
        suspenseScore: 89,
        emotionalScore: 91,
        confidence: 88,
        thumbnail: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=500&q=80',
        dialogueCount: 19,
        tags: ['Snow Fortress', 'Limbo Hazard', 'Vault Infiltration'],
      },
      {
        id: 'scene-045',
        sceneNumber: 45,
        timestampStart: '01:21:16',
        timestampEnd: '01:24:30',
        startSec: 4876,
        endSec: 5070,
        location: 'Limbo - Collapsing Dream Metropolis',
        timeOfDay: 'twilight',
        characters: ['Dom Cobb', 'Mal', 'Ariadne'],
        keyEvent: 'Cobb confronts Mal projection; confesses he implanted the idea that killed her',
        twistScore: 99,
        suspenseScore: 97,
        emotionalScore: 98,
        confidence: 96,
        thumbnail: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=500&q=80',
        dialogueCount: 26,
        tags: ['Limbo', 'Mal Confrontation', 'The Original Inception', 'Totem Spinning'],
      },
    ],
    characters: [
      {
        id: 'char-cobb',
        name: 'Dom Cobb',
        actor: 'Leonardo DiCaprio',
        role: 'protagonist',
        archetype: 'The Extractor / Broken Mind Architect',
        confidence: 98,
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
        screenTimeMinutes: 84.5,
        description: 'Master of dream extraction haunted by the guilt of his wife Mal’s suicide.',
        keyQuote: 'An idea is like a virus. Resilient. Highly contagious.',
      },
      {
        id: 'char-ariadne',
        name: 'Ariadne',
        actor: 'Elliot Page',
        role: 'supporting',
        archetype: 'The Architect / Audience Anchor',
        confidence: 94,
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
        screenTimeMinutes: 52.1,
        description: 'Brilliant student architect who designs complex dream mazes and deciphers Cobb’s subconscious.',
        keyQuote: 'You need to face your memories, Dom. Or they will trap you here.',
      },
      {
        id: 'char-saito',
        name: 'Mr. Saito',
        actor: 'Ken Watanabe',
        role: 'target',
        archetype: 'The Corporate Catalyst / Patron',
        confidence: 88,
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
        screenTimeMinutes: 38.4,
        description: 'Energy tycoon who commissions the inception job on competitor Robert Fischer in exchange for Cobb’s amnesty.',
        keyQuote: 'Do you want to take a leap of faith, or become an old man, filled with regret?',
      },
      {
        id: 'char-fischer',
        name: 'Robert Fischer',
        actor: 'Cillian Murphy',
        role: 'victim',
        archetype: 'The Inception Mark / Vulnerable Heir',
        confidence: 76,
        avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80',
        screenTimeMinutes: 34.2,
        description: 'Heir to Maurice Fischer’s global empire whose deep-seated father wound makes him vulnerable to inception.',
        keyQuote: 'My father wanted me to be my own man, not him.',
      },
      {
        id: 'char-mal',
        name: 'Mal Cobb',
        actor: 'Marion Cotillard',
        role: 'supporting',
        archetype: 'The Shadow / Tragic Specter',
        confidence: 88,
        avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
        screenTimeMinutes: 28.6,
        description: 'Cobb’s deceased wife whose dangerous mental shade sabotages his dream operations from inside.',
        keyQuote: 'You are waiting for a train. A train that will take you far away.',
      },
    ],
    storyGraph: [
      { id: 'cobb', label: 'Dom Cobb', type: 'character', role: 'Protagonist', x: 250, y: 150, connections: ['ariadne', 'saito', 'fischer', 'mal', 'dreams', 'reality'] },
      { id: 'ariadne', label: 'Ariadne', type: 'character', role: 'Architect', x: 120, y: 90, connections: ['cobb', 'dreams'] },
      { id: 'saito', label: 'Saito', type: 'character', role: 'Patron', x: 380, y: 90, connections: ['cobb', 'fischer'] },
      { id: 'fischer', label: 'Fischer', type: 'character', role: 'Mark', x: 420, y: 220, connections: ['saito', 'cobb', 'dreams'] },
      { id: 'mal', label: 'Mal', type: 'character', role: 'Subconscious Shadow', x: 250, y: 270, connections: ['cobb', 'limbo'] },
      { id: 'the_team', label: 'The Extraction Team', type: 'faction', role: 'Operatives', x: 100, y: 230, connections: ['cobb', 'ariadne'] },
      { id: 'dreams', label: 'Dream Worlds (3 Layers)', type: 'concept', role: 'Setting', x: 180, y: 320, connections: ['cobb', 'limbo'] },
      { id: 'reality', label: 'Reality (Totem Rule)', type: 'concept', role: 'Anchor', x: 360, y: 320, connections: ['cobb'] },
      { id: 'limbo', label: 'Limbo (Raw Unconstructed)', type: 'location', role: 'Abyss', x: 250, y: 380, connections: ['mal', 'dreams', 'saito'] },
    ],
    script: {
      id: 'script-inception-01',
      projectId: 'proj-inception',
      targetDurationSec: 1472, // 24:32 target
      actualDurationSec: 1472,
      wordsCount: 3680,
      readingSpeedWpm: 150,
      segments: [
        {
          id: 'seg-1',
          beatId: 'hook',
          title: 'Hook: The Virus of the Mind',
          timestampTarget: '00:00 - 00:48',
          hookLine: 'What if you could enter someone else’s dream, steal their deepest secret—or plant an idea that feels like their own?',
          targetDurationSec: 48,
          status: 'final',
          visualNotes: 'Opening waves crashing on the shore. Cobb waking with face in wet sand. Rapid flash of spinning brass totem.',
          narration: [
            {
              id: 'narr-1',
              text: 'In 2010, Christopher Nolan delivered Inception—a mind-bending masterpiece that redefined cinema storytelling. But underneath its zero-gravity action and folding cities lies an agonizing psychological puzzle: Did Dom Cobb ever actually wake up?',
              voiceActorId: 'voice-titan',
              durationSec: 48,
            },
          ],
        },
        {
          id: 'seg-2',
          beatId: 'intro',
          title: 'Introduction: The Extractor’s Curse',
          timestampTarget: '00:48 - 02:15',
          hookLine: 'Cobb is a thief, but not of money or diamonds. He steals ideas while you sleep.',
          targetDurationSec: 87,
          status: 'final',
          visualNotes: 'Introduce the dream-sharing PASIV device. Slow motion glass shattering in Saito’s Japanese mansion.',
          narration: [
            {
              id: 'narr-2',
              text: 'Dom Cobb is the world’s elite extractor. With a briefcase machine and intravenous sedatives, he taps directly into human subconsciousness during the REM cycle. But theft is easy compared to creation.',
              voiceActorId: 'voice-titan',
              durationSec: 87,
            },
          ],
        },
        {
          id: 'seg-3',
          beatId: 'mission',
          title: 'The Mission: Planting the Seed',
          timestampTarget: '02:15 - 04:32',
          hookLine: 'He is offered one impossible job that could erase his criminal charges and bring him home to his children.',
          targetDurationSec: 137,
          status: 'final',
          visualNotes: 'Helicopter shot over Sydney. Saito laying out the Fischer corporate breakup ultimatum.',
          narration: [
            {
              id: 'narr-3',
              text: 'Saito offers Cobb a clean slate: perform an inception on young heir Robert Fischer. Instead of stealing a thought, plant one so deeply that Fischer dismantles his father’s energy empire of his own free will.',
              voiceActorId: 'voice-titan',
              durationSec: 137,
            },
          ],
        },
        {
          id: 'seg-4',
          beatId: 'team',
          title: 'The Team: Architecture of Deception',
          timestampTarget: '04:32 - 07:18',
          hookLine: 'A team of specialists enters the mind: an architect, a chemist, a forger, and a point man.',
          targetDurationSec: 166,
          status: 'reviewed',
          visualNotes: 'Paris streets folding upside down. Mirrors reflecting infinity. Penrose infinite staircase test.',
          narration: [
            {
              id: 'narr-4',
              text: 'Cobb assembles his crew: Arthur for logistics, Eames for character deception, Yusuf for compound sedatives, and Ariadne—the young prodigy who must craft dreams with impossible non-Euclidean geometry.',
              voiceActorId: 'voice-titan',
              durationSec: 166,
            },
          ],
        },
        {
          id: 'seg-5',
          beatId: 'twist',
          title: 'The Twist: The Militarized Subconscious',
          timestampTarget: '07:18 - 12:45',
          hookLine: 'Things are not what they seem: Fischer had his subconscious trained to kill intruders.',
          targetDurationSec: 327,
          status: 'reviewed',
          visualNotes: 'Rain-slicked city streets, freight train bursting through asphalt. Saito hit by sniper bullet.',
          narration: [
            {
              id: 'narr-5',
              text: 'The moment they kidnap Fischer on Level One, armed bodyguards attack. Fischer has had anti-extraction tactical training. Worse: because the sedative is so heavy, dying won’t wake them up. It will plunge them into Limbo—an endless abyss of unconstructed dream space.',
              voiceActorId: 'voice-titan',
              durationSec: 327,
            },
          ],
        },
        {
          id: 'seg-6',
          beatId: 'climax',
          title: 'Climax: Three Levels in Freefall',
          timestampTarget: '12:45 - 18:32',
          hookLine: 'The line between dream and reality disappears across three simultaneous ticking clocks.',
          targetDurationSec: 347,
          status: 'reviewed',
          visualNotes: 'Split screen logic: Van falling off bridge, Arthur fighting in tumbling zero-g hallway, snow fortress ski battle.',
          narration: [
            {
              id: 'narr-6',
              text: 'In one of the greatest editing achievements in modern cinema, Nolan intercuts three distinct dream planes, each moving at different time dilations. Ten seconds in the van equals three minutes in the hotel, and an hour at the snow fortress.',
              voiceActorId: 'voice-titan',
              durationSec: 347,
            },
          ],
        },
        {
          id: 'seg-7',
          beatId: 'reveal',
          title: 'Reveal: The Original Inception',
          timestampTarget: '18:32 - 23:10',
          hookLine: 'The shocking truth was hidden in plain sight: Cobb has performed inception before.',
          targetDurationSec: 278,
          status: 'final',
          visualNotes: 'Cobb placing the spinning totem in Mal’s dollhouse safe. Mal perched on the window ledge of hotel suite.',
          narration: [
            {
              id: 'narr-7',
              text: 'Cobb confesses his fatal guilt to Ariadne: when he and Mal lived fifty years in Limbo, Mal refused to leave. To convince her that her world was fake, Cobb broke into her mental vault and spun her totem. It worked—too well. Even in the real world, she couldn’t stop believing she was asleep.',
              voiceActorId: 'voice-titan',
              durationSec: 278,
            },
          ],
        },
        {
          id: 'seg-8',
          beatId: 'ending',
          title: 'Ending: The Spinning Totem Decoded',
          timestampTarget: '23:10 - 24:32',
          hookLine: 'And in the end, does the top fall? Or does Dom Cobb no longer care?',
          targetDurationSec: 82,
          status: 'final',
          visualNotes: 'LAX customs stamp. Cobb greeting his children in the garden. Close up on the spinning brass top as it wobbles, cuts to black.',
          narration: [
            {
              id: 'narr-8',
              text: 'The famous final shot. Cobb spins the top on the table, walks away to hug his children, and doesn’t look back. Whether the top falls is irrelevant: Cobb has chosen his reality. He has finally let Mal go.',
              voiceActorId: 'voice-titan',
              durationSec: 82,
            },
          ],
        },
      ],
    },
    timeline: {
      id: 'time-inception-01',
      projectId: 'proj-inception',
      totalDuration: 1472, // 24:32
      currentTime: 245,
      isPlaying: false,
      zoomLevel: 4,
      tracks: [
        {
          id: 'track-video',
          name: 'Video',
          type: 'video',
          muted: false,
          solo: false,
          locked: false,
          volume: 100,
          clips: [
            { id: 'v-clip-1', trackId: 'track-video', title: 'Scene 001 - Beach Shore Intro', startTime: 0, duration: 48, sourceStart: 12, sourceEnd: 60, mediaType: 'video', color: '#0ea5e9', thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=200&q=80' },
            { id: 'v-clip-2', trackId: 'track-video', title: 'Scene 008 - Dream Extractor Rules', startTime: 48, duration: 87, sourceStart: 210, sourceEnd: 297, mediaType: 'video', color: '#0284c7', thumbnail: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=200&q=80' },
            { id: 'v-clip-3', trackId: 'track-video', title: 'Scene 024 - Paris Folding Cityscape', startTime: 135, duration: 166, sourceStart: 890, sourceEnd: 1056, mediaType: 'video', color: '#06b6d4', thumbnail: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=200&q=80' },
            { id: 'v-clip-4', trackId: 'track-video', title: 'Scene 042 - Rain Van Ambush', startTime: 301, duration: 250, sourceStart: 4472, sourceEnd: 4722, mediaType: 'video', color: '#3b82f6', thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=200&q=80' },
            { id: 'v-clip-5', trackId: 'track-video', title: 'Scene 043 - Rotating Corridor Fight', startTime: 551, duration: 280, sourceStart: 4723, sourceEnd: 5003, mediaType: 'video', color: '#6366f1', thumbnail: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=200&q=80' },
            { id: 'v-clip-6', trackId: 'track-video', title: 'Scene 045 - Limbo City Breakdown', startTime: 831, duration: 320, sourceStart: 5004, sourceEnd: 5324, mediaType: 'video', color: '#8b5cf6', thumbnail: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=200&q=80' },
            { id: 'v-clip-7', trackId: 'track-video', title: 'Scene 060 - Totem Spin Climax', startTime: 1151, duration: 321, sourceStart: 8400, sourceEnd: 8721, mediaType: 'video', color: '#00f0ff', thumbnail: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=200&q=80' },
          ],
        },
        {
          id: 'track-narration',
          name: 'Narration',
          type: 'narration',
          muted: false,
          solo: false,
          locked: false,
          volume: 95,
          clips: [
            { id: 'n-clip-1', trackId: 'track-narration', title: 'Ares - Hook Narration', startTime: 2, duration: 44, sourceStart: 0, sourceEnd: 44, mediaType: 'narration', color: '#10b981', waveform: [20, 45, 80, 60, 95, 30, 75, 40, 65, 85, 20, 50, 90, 70, 40] },
            { id: 'n-clip-2', trackId: 'track-narration', title: 'Ares - Intro Extractor Lore', startTime: 50, duration: 80, sourceStart: 0, sourceEnd: 80, mediaType: 'narration', color: '#10b981', waveform: [40, 60, 70, 50, 85, 60, 40, 75, 90, 55, 60, 80, 70, 30, 85] },
            { id: 'n-clip-3', trackId: 'track-narration', title: 'Ares - Mission Inception Setup', startTime: 138, duration: 155, sourceStart: 0, sourceEnd: 155, mediaType: 'narration', color: '#10b981', waveform: [35, 75, 55, 90, 65, 45, 80, 85, 70, 60, 95, 40, 80, 65, 50] },
            { id: 'n-clip-4', trackId: 'track-narration', title: 'Ares - Multi-Layer Freefall Climax', startTime: 305, duration: 240, sourceStart: 0, sourceEnd: 240, mediaType: 'narration', color: '#10b981', waveform: [60, 90, 85, 95, 70, 85, 90, 65, 80, 95, 70, 85, 90, 60, 75] },
            { id: 'n-clip-5', trackId: 'track-narration', title: 'Ares - Ending Philosophy Reveal', startTime: 835, duration: 310, sourceStart: 0, sourceEnd: 310, mediaType: 'narration', color: '#10b981', waveform: [50, 70, 60, 80, 65, 90, 75, 55, 85, 60, 70, 80, 90, 60, 40] },
          ],
        },
        {
          id: 'track-dialogue',
          name: 'Dialogue',
          type: 'dialogue',
          muted: false,
          solo: false,
          locked: false,
          volume: 85,
          clips: [
            { id: 'd-clip-1', trackId: 'track-dialogue', title: 'Cobb: An idea is like a virus', startTime: 15, duration: 8, sourceStart: 120, sourceEnd: 128, mediaType: 'dialogue', color: '#06b6d4', waveform: [10, 40, 85, 90, 60, 30, 10] },
            { id: 'd-clip-2', trackId: 'track-dialogue', title: 'Saito: Take a leap of faith', startTime: 160, duration: 7, sourceStart: 890, sourceEnd: 897, mediaType: 'dialogue', color: '#06b6d4', waveform: [15, 60, 75, 80, 50, 20] },
            { id: 'd-clip-3', trackId: 'track-dialogue', title: 'Mal: You are waiting for a train', startTime: 900, duration: 12, sourceStart: 5040, sourceEnd: 5052, mediaType: 'dialogue', color: '#06b6d4', waveform: [20, 55, 70, 85, 95, 60, 30] },
          ],
        },
        {
          id: 'track-sfx',
          name: 'SFX',
          type: 'sfx',
          muted: false,
          solo: false,
          locked: false,
          volume: 75,
          clips: [
            { id: 'sfx-clip-1', trackId: 'track-sfx', title: 'Brass BRAAAM Horn Hit', startTime: 0, duration: 5, sourceStart: 0, sourceEnd: 5, mediaType: 'sfx', color: '#f59e0b', waveform: [95, 90, 80, 60, 30] },
            { id: 'sfx-clip-2', trackId: 'track-sfx', title: 'Sub-bass Dream Drop', startTime: 47, duration: 6, sourceStart: 0, sourceEnd: 6, mediaType: 'sfx', color: '#f59e0b', waveform: [80, 95, 85, 60, 20] },
            { id: 'sfx-clip-3', trackId: 'track-sfx', title: 'Corridor Gravity Thuds', startTime: 552, duration: 40, sourceStart: 0, sourceEnd: 40, mediaType: 'sfx', color: '#f59e0b', waveform: [30, 80, 40, 90, 50, 85, 30, 95, 40] },
            { id: 'sfx-clip-4', trackId: 'track-sfx', title: 'Totem Wobble & Blackout', startTime: 1460, duration: 12, sourceStart: 0, sourceEnd: 12, mediaType: 'sfx', color: '#f59e0b', waveform: [50, 60, 40, 50, 30, 20, 10] },
          ],
        },
        {
          id: 'track-music',
          name: 'Music',
          type: 'music',
          muted: false,
          solo: false,
          locked: false,
          volume: 50,
          clips: [
            { id: 'm-clip-1', trackId: 'track-music', title: 'Time - Hans Zimmer (Remastered Suite)', startTime: 0, duration: 600, sourceStart: 0, sourceEnd: 600, mediaType: 'music', color: '#ec4899', waveform: [20, 30, 40, 50, 60, 75, 85, 95, 90, 80, 70, 60] },
            { id: 'm-clip-2', trackId: 'track-music', title: 'Mind Heist Orchestral Tension', startTime: 600, duration: 872, sourceStart: 0, sourceEnd: 872, mediaType: 'music', color: '#ec4899', waveform: [40, 60, 80, 70, 85, 95, 80, 90, 70, 85, 95, 60] },
          ],
        },
        {
          id: 'track-subtitles',
          name: 'Subtitles',
          type: 'subtitles',
          muted: false,
          solo: false,
          locked: false,
          volume: 100,
          clips: [
            { id: 'sub-clip-1', trackId: 'track-subtitles', title: 'Captions: Hook 0-48s', startTime: 0, duration: 48, sourceStart: 0, sourceEnd: 48, mediaType: 'subtitles', color: '#a855f7' },
            { id: 'sub-clip-2', trackId: 'track-subtitles', title: 'Captions: Intro 48-135s', startTime: 48, duration: 87, sourceStart: 0, sourceEnd: 87, mediaType: 'subtitles', color: '#a855f7' },
            { id: 'sub-clip-3', trackId: 'track-subtitles', title: 'Captions: Freefall 135-301s', startTime: 135, duration: 166, sourceStart: 0, sourceEnd: 166, mediaType: 'subtitles', color: '#a855f7' },
            { id: 'sub-clip-4', trackId: 'track-subtitles', title: 'Captions: Climax & End', startTime: 301, duration: 1171, sourceStart: 0, sourceEnd: 1171, mediaType: 'subtitles', color: '#a855f7' },
          ],
        },
      ],
    },
    subtitles: [
      { id: 'sub-1', startTime: '00:00:02.100', endTime: '00:00:08.500', startSec: 2.1, endSec: 8.5, text: 'In 2010, Christopher Nolan delivered Inception—a psychological puzzle.', confidence: 99, stylePreset: 'cyber_cyan' },
      { id: 'sub-2', startTime: '00:00:09.000', endTime: '00:00:15.800', startSec: 9.0, endSec: 15.8, text: 'What if your dreams weren’t just dreams, but vulnerable architecture?', confidence: 98, stylePreset: 'karaoke_glow' },
      { id: 'sub-3', startTime: '00:00:16.200', endTime: '00:00:24.400', startSec: 16.2, endSec: 24.4, text: 'Dom Cobb is an extractor: he steals corporate secrets from inside the subconscious.', confidence: 97, stylePreset: 'bold_sans' },
      { id: 'sub-4', startTime: '00:00:25.000', endTime: '00:00:32.100', startSec: 25.0, endSec: 32.1, text: 'To return to his children, he must achieve the impossible: Inception.', confidence: 98, stylePreset: 'cinema_yellow' },
    ],
    shorts: [
      {
        id: 'short-1',
        title: 'Why Cobb Never Woke Up in Inception',
        targetDuration: 58,
        viralHook: 'The spinning top was NEVER Cobb’s totem! Here is the undeniable proof.',
        format: '9:16',
        coverUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=400&q=80',
        status: 'ready',
        timestampRange: '18:32 - 19:30',
        tags: ['#InceptionExplained', '#MovieTheories', '#ChristopherNolan', '#Mindblown'],
      },
      {
        id: 'short-2',
        title: 'The Real Meaning of Nolan’s Penrose Staircase',
        targetDuration: 42,
        viralHook: 'Paradox architecture in cinema explained in 40 seconds.',
        format: '9:16',
        coverUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=400&q=80',
        status: 'ready',
        timestampRange: '05:10 - 05:52',
        tags: ['#FilmAnalysis', '#CinemaTricks', '#Inception', '#Shorts'],
      },
      {
        id: 'short-3',
        title: 'How They Filmed the Zero-G Hallway Without CGI',
        targetDuration: 54,
        viralHook: 'Christopher Nolan built a 100-foot rotating centrifuge hotel room!',
        format: '9:16',
        coverUrl: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=400&q=80',
        status: 'ready',
        timestampRange: '13:15 - 14:09',
        tags: ['#BehindTheScenes', '#PracticalEffects', '#Nolan', '#MovieLovers'],
      },
    ],
    thumbnails: [
      {
        id: 'thumb-1',
        variant: 'A',
        title: 'High Intrigue Cutout',
        overlayText: 'DID HE WAKE UP?',
        badgeText: '98% REVEAL',
        imageUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=800&q=80',
        predictedCtr: 14.2,
        active: true,
      },
      {
        id: 'thumb-2',
        variant: 'B',
        title: 'Totem Secret Macro',
        overlayText: 'THE REAL TOTEM',
        badgeText: 'NOT THE TOP!',
        imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80',
        predictedCtr: 16.8,
        active: false,
      },
      {
        id: 'thumb-3',
        variant: 'C',
        title: 'Limbo City Shock',
        overlayText: 'THE 50 YEAR TRAP',
        badgeText: 'TRUE ENDING',
        imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
        predictedCtr: 12.5,
        active: false,
      },
    ],
    seo: {
      titleVariants: [
        { title: 'INCEPTION Ending Explained: The Truth Nolan Hid In Plain Sight', score: 98 },
        { title: 'Why Dom Cobb Never Woke Up (Inception Mind-Bending Breakdown)', score: 94 },
        { title: 'Inception Full Movie Explainer: Every Dream Layer Decoded', score: 91 },
      ],
      descriptions: [
        'Did Dom Cobb ever truly wake up from Limbo? In this definitive cinema analysis of Christopher Nolan\'s Inception (2010), we break down the 3 dream layers, the rules of totems, why the brass top was never Cobb\'s real anchor, and the psychological truth behind the final shot.\n\n⏱️ CHAPTERS:\n00:00 The Virus of the Mind\n00:48 The Extractor\'s Curse\n02:15 The Mission to Incept Fischer\n04:32 The Team and Architecture\n07:18 The Militarized Subconscious\n12:45 Three Levels in Freefall\n18:32 The Original Inception on Mal\n23:10 The Spinning Totem Decoded\n\n#Inception #ChristopherNolan #MovieEndingExplained #TheDevilsEye',
      ],
      tags: [
        'Inception explained',
        'Inception ending explained',
        'Christopher Nolan',
        'Dom Cobb totem',
        'Inception dream layers',
        'did Cobb wake up',
        'Leonardo DiCaprio',
        'cinema intelligence',
        'movie breakdown',
        'film analysis',
      ],
      chapters: [
        { timestamp: '00:00', title: 'The Virus of the Mind' },
        { timestamp: '00:48', title: 'The Extractor\'s Curse' },
        { timestamp: '02:15', title: 'The Mission to Incept Fischer' },
        { timestamp: '04:32', title: 'The Team & Architecture' },
        { timestamp: '07:18', title: 'The Militarized Subconscious' },
        { timestamp: '12:45', title: 'Three Levels in Freefall' },
        { timestamp: '18:32', title: 'The Original Inception on Mal' },
        { timestamp: '23:10', title: 'The Spinning Totem Decoded' },
      ],
      viralHooks: [
        'Did you know Cobb\'s wedding ring only appears when he is dreaming?',
        'Christopher Nolan confirmed the true meaning of the ending during a Princeton commencement speech.',
        'The song Edith Piaf is slowed down to become the massive orchestral horn theme throughout the movie.',
      ],
      overallSeoScore: 96,
    },
  },
  {
    id: 'proj-interstellar',
    title: 'Interstellar: The Fifth Dimension & Time Dilation',
    type: 'movie',
    director: 'Christopher Nolan',
    year: 2014,
    genre: ['Sci-Fi', 'Drama', 'Adventure'],
    synopsis: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival as Earth faces ecological collapse.',
    duration: '02:49:00',
    durationSec: 10140,
    resolution: '4K UHD (3840x2160)',
    fps: 24,
    posterUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80',
    videoSourceUrl: 'Interstellar_4K.mkv',
    status: 'analyzed',
    lastEdited: '2 hours ago',
    createdAt: '2026-09-07',
    analysis: {
      overallScore: 89,
      charactersCount: 8,
      keyEventsCount: 42,
      twistsCount: 5,
      suspensePointsCount: 16,
      emotionalMomentsCount: 12,
      narrationSyncScore: 92,
      sceneMatchingScore: 91,
      audioScore: 95,
      subtitlesScore: 93,
      pacingScore: 88,
      continuityScore: 92,
    },
    scenes: [],
    characters: [],
    storyGraph: [],
    script: { id: 'script-interstellar', projectId: 'proj-interstellar', targetDurationSec: 1200, actualDurationSec: 0, wordsCount: 0, readingSpeedWpm: 150, segments: [] },
    timeline: { id: 'time-interstellar', projectId: 'proj-interstellar', totalDuration: 1200, currentTime: 0, isPlaying: false, zoomLevel: 3, tracks: [] },
    subtitles: [],
    shorts: [],
    thumbnails: [],
    seo: { titleVariants: [], descriptions: [], tags: [], chapters: [], viralHooks: [], overallSeoScore: 88 },
  },
  {
    id: 'proj-dark-series',
    title: 'Dark: The Complete 33-Year Chrono Knot',
    type: 'web_series',
    director: 'Baran bo Odar',
    year: 2017,
    genre: ['Mystery', 'Sci-Fi', 'Thriller', 'German Drama'],
    synopsis: 'A family saga with a supernatural twist, set in a German town where the disappearance of two young children exposes the relationships among four families across multiple generations.',
    duration: '3 Seasons (26 Episodes)',
    durationSec: 78000,
    resolution: '4K HDR (3840x2160)',
    fps: 25,
    posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
    status: 'scripting',
    lastEdited: 'Yesterday',
    createdAt: '2026-09-05',
    activeEpisodeId: 'ep-s1e1',
    episodes: [
      { id: 'ep-s1e1', seasonNumber: 1, episodeNumber: 1, title: 'Secrets', duration: '51:00', durationSec: 3060, status: 'ready', synopsis: 'In 2019, a local boy\'s disappearance stokes fear in the residents of Winden.', thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=300&q=80' },
      { id: 'ep-s1e2', seasonNumber: 1, episodeNumber: 2, title: 'Lies', duration: '44:00', durationSec: 2640, status: 'ready', synopsis: 'Grim discoveries leave police baffled as old secrets resurface.', thumbnail: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=300&q=80' },
      { id: 'ep-s1e3', seasonNumber: 1, episodeNumber: 3, title: 'Past and Present', duration: '46:00', durationSec: 2760, status: 'analyzed', synopsis: 'It is 1986, and Mikkel encounters young versions of his parents.', thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=300&q=80' },
      { id: 'ep-s1e4', seasonNumber: 1, episodeNumber: 4, title: 'Double Lives', duration: '48:00', durationSec: 2880, status: 'scripting', synopsis: 'Bizarre occurrences trigger a sense of déjà vu for Charlotte.', thumbnail: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=300&q=80' },
      { id: 'ep-s1e5', seasonNumber: 1, episodeNumber: 5, title: 'Truths', duration: '45:00', durationSec: 2700, status: 'ingesting', synopsis: 'Hannah takes her obsession with Ulrich to the next level.', thumbnail: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=300&q=80' },
    ],
    analysis: {
      overallScore: 95,
      charactersCount: 32,
      keyEventsCount: 84,
      twistsCount: 19,
      suspensePointsCount: 31,
      emotionalMomentsCount: 22,
      narrationSyncScore: 95,
      sceneMatchingScore: 93,
      audioScore: 94,
      subtitlesScore: 98,
      pacingScore: 94,
      continuityScore: 97,
    },
    scenes: [],
    characters: [],
    storyGraph: [],
    script: { id: 'script-dark', projectId: 'proj-dark-series', targetDurationSec: 2400, actualDurationSec: 0, wordsCount: 0, readingSpeedWpm: 150, segments: [] },
    timeline: { id: 'time-dark', projectId: 'proj-dark-series', totalDuration: 2400, currentTime: 0, isPlaying: false, zoomLevel: 3, tracks: [] },
    subtitles: [],
    shorts: [],
    thumbnails: [],
    seo: { titleVariants: [], descriptions: [], tags: [], chapters: [], viralHooks: [], overallSeoScore: 92 },
  },
];
